### ISSUE TITLE
Error message when attempting to boost post with bot [step 6]

### ISSUE THREAD

**Issue by Poudlardo** [mahomedalid/raccoonbits#3]
I passed step 1 to 5 succesfully without problems. When it was time to wake up the bot in the step 6, here was the error I got :   
![Capture d'écran 2024-02-02 180116](https://github.com/mahomedalid/raccoonbits/assets/55178305/eda1c9cd-e432-4f10-b50e-02ab7e2cf1dc)

Here are the permissions I enabled.
![image](https://github.com/mahomedalid/raccoonbits/assets/55178305/9292afdc-4064-4a66-910c-27047324317a)
Also, I checked to make sure and, the access key is the one for my bot account, not my personal profile.

**Comment by mahomedalid** [comment]
Thanks for reporting this!

I see the problem, I am not correctly sanitizing/converting/formatting the input. I asume you are in Europe, and dotnet uses commas for decimals. I will release a fix later today.
